### ISSUE TITLE
Instantly show ripples

### ISSUE THREAD

**Issue by lorisgir** [hosein-nadali/flutter-wave-blob#2]
Hi, thanks for this library.
The initials ripples takes a few seconds to fully appear. Is there a way to instantly show them?
I tried to increment the speed but it's not enough.

**Comment by hosein-nadali** [comment]
Hi, thanks @lorisgir
it's not a issue, it's a library feature.
But i will work on it in next version

**Comment by lorisgir** [comment]
Yea I imagined. Reading the code I couldn't figure out which parameter needed to be tuned to achieve what I need.
Could you point me in the right direction?

**Comment by hosein-nadali** [comment]
Unfortunately there isn't any parameter for disable this feature.
As i said i'll add in next version.

**Comment by lorisgir** [comment]
Thank you so much!
